name: hex_place
description: "Collective artistry on a virtual canvas made of Hexagons"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.1+3

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.21.0
  universal_html: ^2.2.4
  intl: ^0.19.0
  flutter_lints: ^5.0.0
  socket_io_client: ^3.0.0
  flutter_simple_dependency_injection: ^2.0.0
  url_strategy: ^0.3.0  # TODO: replace?
  url_launcher: ^6.3.1
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  http_client: ^1.5.3
  dio: ^5.7.0
  oktoast: ^3.4.0
  jwt_decode: ^0.3.1
  get_it: ^8.0.1
  tuple: ^2.0.2
  image: ^4.3.0
  file_picker: ^8.1.3
  isolated_worker: ^0.1.1
  dropdown_button2: ^2.3.9
  back_button_interceptor: ^7.0.3
  quiver: ^3.2.2
  google_sign_in: ^6.2.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  syncfusion_flutter_sliders: ^27.1.56
  sign_in_with_apple: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/images/hex_place_icon_android.png"
  image_path_ios: "assets/images/hex_place_icon.png"
  adaptive_icon_background: "assets/images/hex_place_icon_android.png"
  adaptive_icon_foreground: "assets/images/hex_place_icon_android.png"
  web:
    generate: true
    image_path: "assets/images/hex_place_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/hex_place_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/hex_place_icon.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/tile_variants/flat_top.png
    - assets/images/tile_variants/point_top.png
    - assets/images/tiles_flat_top/flat_000000.png
    - assets/images/tiles_flat_top/flat_ffffff.png
    - assets/images/tiles_flat_top/flat_00a368.png
    - assets/images/tiles_flat_top/flat_00756f.png
    - assets/images/tiles_flat_top/flat_00cc78.png
    - assets/images/tiles_flat_top/flat_009eaa.png
    - assets/images/tiles_flat_top/flat_ff4500.png
    - assets/images/tiles_flat_top/flat_ffa800.png
    - assets/images/tiles_flat_top/flat_be0039.png
    - assets/images/tiles_flat_top/flat_ff3881.png
    - assets/images/tiles_flat_top/flat_6a5cff.png
    - assets/images/tiles_flat_top/flat_ff99aa.png
    - assets/images/tiles_flat_top/flat_ffd635.png
    - assets/images/tiles_flat_top/flat_b44ac0.png
    - assets/images/tiles_flat_top/flat_51e9f4.png
    - assets/images/tiles_flat_top/flat_493ac1.png
    - assets/images/tiles_flat_top/flat_898d90.png
    - assets/images/tiles_flat_top/flat_d4d7d9.png
    - assets/images/tiles_flat_top/flat_7eed56.png
    - assets/images/tiles_flat_top/flat_9c6926.png
    - assets/images/tiles_flat_top/flat_811e9f.png
    - assets/images/tiles_flat_top/flat_6d482f.png
    - assets/images/tiles_flat_top/flat_2450a4.png
    - assets/images/tiles_flat_top/flat_3690ea.png
    - assets/images/brocast_transparent.png
    - assets/images/Github_logo_PNG1.png
    - assets/images/google_button.png
    - assets/images/apple_button.png
    - assets/images/reddit_button.png
    - assets/images/github_button.png
    - assets/images/default_avatar.png
    - assets/images/ui/gold_shield_frame.png
    - assets/images/ui/hexagon_frame_small_fill.png
    - assets/images/ui/icon/globe_icon_no_colour.png
    - assets/images/ui/icon/friend_icon_clean.png
    - assets/images/ui/icon/message_icon_clean.png
    - assets/images/ui/icon/update_notification.png
    - assets/images/ui/icon/guild_icon_clean.png
    - assets/images/ui/icon/shield_default.png
    - assets/images/hex_place_logo.png
